--1
SELECT * FROM S ORDER BY CITY DESC;
--2
SELECT * FROM S ORDER BY CITY , NAME ASC;
--3
SELECT * FROM S WHERE Status BETWEEN 10 AND 20;
SELECT * FROM S WHERE Status>=10 AND Status<=20;
--4
SELECT Pname , Weight FROM P WHERE Weight NOT BETWEEN 10 AND 15;
--5
SELECT * FROM P WHERE upper(Pname)>='S' AND upper(Pname)<'T';
SELECT * FROM P WHERE upper(Pname) LIKE 'S%';
--6
SELECT * FROM S WHERE CITY LIKE 'L%';
--7
SELECT * FROM J WHERE Jname LIKE '__n%';
