--1
SELECT MIN(STATUS) FROM S;
--2
SELECT MAX(Weight) FROM P;
--3
SELECT AVERAGE(Weight) FROM P;
--4
SELECT SUM(QTY) FROM sp WHERE `P#` = 'P1';
--5
SELECT `P#` ,SUM(QTY) as COUNT
FROM sp 
GROUP BY `P#`;
--6
SELECT `P#` , AVG(QTY) FROM sp 
GROUP BY `P#`;
--7
SELECT `P#`,MAX(QTY) FROM sp
GROUP BY `P#`
HAVING SUM(QTY) > 800;
--8 
SELECT Status,COUNT(*) FROM S
GROUP BY Status;
--9
--10
SELECT COUNT(*),COUNT(Status) FROM S;
--11
SELECT CASE
WHEN Status=10 THEN 'TEN'
WHEN Status=20 THEN 'TWENTY'
WHEN Status=30 THEN 'THIRTY'
ELSE Status
END AS STATUS,
COUNT(Status)
FROM S
GROUP BY Status; 