USE SALESDB;
--1
SELECT cname,city,"HIGH RATING" AS rating FROM CUSTOMER
WHERE rating >= 200
UNION 
SELECT cname,city,"LOW RATING" AS rating FROM CUSTOMER
WHERE rating < 200;
--2
SELECT CUSTOMER.cname as name,CUSTOMER.cnum as num
FROM CUSTOMER,ORDERS
WHERE CUSTOMER.cnum = ORDERS.cnum
GROUP BY cname,CUSTOMER.cnum
HAVING COUNT(CUSTOMER.cnum) > 1
UNION
SELECT SALESPEOPLE.sname as name,SALESPEOPLE.snum as num
FROM SALESPEOPLE,ORDERS
WHERE SALESPEOPLE.snum = SALESPEOPLE.snum
GROUP BY sname,SALESPEOPLE.snum
HAVING COUNT(SALESPEOPLE.snum) > 1;
--3
SELECT SALESPEOPLE.snum num FROM SALESPEOPLE WHERE SALESPEOPLE.city = 'San Jose'
UNION DISTINCT 
SELECT CUSTOMER.cnum num FROM CUSTOMER WHERE CUSTOMER.city = 'San Jose'
UNION
SELECT ORDERS.onum FROM ORDERS WHERE ORDERS.odate='1990-10-03';