--1
SELECT * FROM CUSTOMER
WHERE 
rating >= any(
    SELECT rating FROM CUSTOMER,SALESPEOPLE 
    WHERE CUSTOMER.snum = SALESPEOPLE.snum
    AND LOWER(SALESPEOPLE.sname) = 'serres'
);
--2
SELECT Sname 
FROM SALESPEOPLE
WHERE LOWER(city) != ALL
(SElECT LOWER(city) FROM CUSTOMER);
SELECT Sname 
FROM SALESPEOPLE
WHERE LOWER(city) != ANY
(SElECT LOWER(city) FROM CUSTOMER);
--3
SELECT * FROM ORDERS
WHERE amt > Any (
    SELECT amt FROM ORDERS,CUSTOMER
    WHERE ORDERS.cnum = CUSTOMER.cnum
    AND CUSTOMER.city  = 'London'
);
--4
SELECT * FROM ORDERS
WHERE amt > Any (
    SELECT MIN(amt) FROM ORDERS,CUSTOMER
    WHERE ORDERS.cnum = CUSTOMER.cnum
    AND CUSTOMER.city  = 'London'
);