--1
CREATE TABLE MULTICUST
as 
SELECT * FROM SALESPEOPLE 
WHERE Snum in (
    SELECT Snum FROM CUSTOMER GROUP BY Snum HAVING COUNT(*) > 1
);
--2
DELETE FROM CUSTOMER 
WHERE Cnum NOT IN (SELECT Cnum FROM ORDERS);
--3
UPDATE SALESPEOPLE SET comm = comm + 0.20
WHERE Snum IN (SELECT Snum FROM ORDERS GROUP BY Snum HAVING SUM(amt) > 3000);