--1
SELECT * 
FROM ORDERS
WHERE ORDERS.cnum = 
(SELECT cnum FROM CUSTOMER WHERE lower(cname) = 'cisneros');
--2
SELECT DISTINCT cname,rating 
FROM CUSTOMER,ORDERS
WHERE CUSTOMER.cnum = ORDERS.cnum
AND AMT > (
    SELECT AVG(AMT) FROM ORDERS
);
SELECT cname,rating 
FROM CUSTOMER
WHERE cnum IN (
    SELECT cnum 
    FROM  ORDERS
    WHERE AMT > (
        SELECT AVG(AMT) FROM ORDERS
    ));
--3
SELECT snum,SUM(AMT) 
FROM ORDERS
GROUP BY snum
HAVING SUM(AMT) > 
(SELECT MAX(AMT) FROM ORDERS);
